package wakeword

import (
	"bufio"
	"math"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"

	"github.com/go-audio/wav"
)

// TestOpenWakeWord_ParityWithPython feeds a synthetic 3-second WAV through
// the Go pipeline and compares each 80 ms score against a fixture generated
// by the Python reference (src/wake_word) using the same audio and the same
// hey_rex.onnx model.
//
// The fixture is regenerated by the snippet in testdata/README if the model
// or audio changes. The tolerance is intentionally loose (±0.01 absolute)
// because ONNX runtime versions can introduce small numeric differences.
func TestOpenWakeWord_ParityWithPython(t *testing.T) {
	ww := openWakeWordForTest(t)
	defer ww.Close()

	samples := loadTestWAV(t, filepath.Join("testdata", "synthetic.wav"))
	want := loadGoldenScores(t, filepath.Join("testdata", "synthetic_scores.txt"))

	var got []float32
	for i := 0; i+ChunkSamples <= len(samples); i += ChunkSamples {
		score, err := ww.Predict(samples[i : i+ChunkSamples])
		if err != nil {
			t.Fatalf("Predict(chunk %d): %v", i/ChunkSamples, err)
		}
		got = append(got, score)
	}

	if len(got) < len(want) {
		t.Fatalf("produced %d scores, want %d", len(got), len(want))
	}

	const tolerance = 0.01
	for i := range want {
		diff := math.Abs(float64(got[i] - want[i]))
		if diff > tolerance {
			t.Errorf("chunk %d: Go=%.6f Python=%.6f diff=%.6f (tolerance %.3f)",
				i, got[i], want[i], diff, tolerance)
		}
	}
}

func loadTestWAV(t *testing.T, path string) []int16 {
	t.Helper()
	f, err := os.Open(path)
	if err != nil {
		t.Fatalf("open %s: %v", path, err)
	}
	t.Cleanup(func() { _ = f.Close() })

	d := wav.NewDecoder(f)
	if !d.IsValidFile() {
		t.Fatalf("invalid wav: %s", path)
	}
	buf, err := d.FullPCMBuffer()
	if err != nil {
		t.Fatalf("decode wav: %v", err)
	}
	if d.SampleRate != 16000 {
		t.Fatalf("wav sample rate = %d, want 16000", d.SampleRate)
	}
	if d.NumChans != 1 {
		t.Fatalf("wav channels = %d, want 1 (mono)", d.NumChans)
	}
	out := make([]int16, len(buf.Data))
	for i, v := range buf.Data {
		out[i] = int16(v)
	}
	return out
}

func loadGoldenScores(t *testing.T, path string) []float32 {
	t.Helper()
	f, err := os.Open(path)
	if err != nil {
		t.Fatalf("open %s: %v", path, err)
	}
	defer f.Close()

	var out []float32
	s := bufio.NewScanner(f)
	for s.Scan() {
		line := strings.TrimSpace(s.Text())
		if line == "" {
			continue
		}
		v, err := strconv.ParseFloat(line, 32)
		if err != nil {
			t.Fatalf("parse %q: %v", line, err)
		}
		out = append(out, float32(v))
	}
	if err := s.Err(); err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	return out
}
